name: Run dbt test suite on PRs

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  push:
    branches:
      - '!main'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DBT_PROFILES_DIR: ./coffee_shop  # Specify the location of the profiles.yml file
      DBT_PROJECT_DIR: ./coffee_shop  # Specify the location of the project directory
      SCHEMA_PREFIX: dbt_oriana_ga_pr  # Specify the prefix for the PR schema
      PROJECT_ID: ${{ secrets.BIGQUERY_PROJECT_ID }}  # Update with the name of the secret containing the project ID
      SERVICE_ACCOUNT_KEY: ${{ secrets.BIGQUERY_SERVICE_ACCOUNT_KEY }}  # Update with the name of the secret containing the service account key
      
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # Checkout the specific commit of the pull request

      - name: Create GCP keyfile JSON
        run: | # Creates the keyfile and moves it to the profiles directory
          echo "$SERVICE_ACCOUNT_KEY" > gcp-credentials.json
          mv gcp-credentials.json $DBT_PROFILES_DIR 

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11  # Choose the Python version you need

      - name: Install requirements
        run: |
          pip install -r requirements.txt

      - name: Configure dbt Profile
        run: |
          PR_SCHEMA="${{ env.SCHEMA_PREFIX }}_${{ github.event.number }}"
          echo "
          coffee_shop:
            target: ci
            outputs:
              ci:
                type: bigquery
                method: service-account
                keyfile: $DBT_PROFILES_DIR/gcp-credentials.json
                project: $PROJECT_ID
                dataset: $PR_SCHEMA
                threads: 4
                timeout_seconds: 300
          " > $DBT_PROFILES_DIR/profiles.yml

      - name: Run dbt build
        run: |
          dbt build --profiles-dir "$DBT_PROFILES_DIR" --target ci --project-dir "$DBT_PROJECT_DIR"