name: Run production models, update dbt docs, and clean up CI schemas when a PR is merged

on:
  pull_request:
    types: 
      - closed
  push:
    branches:
      - main

env:
  DBT_PROFILES_DIR: ./coffee_shop  # Specify the location of the profiles.yml file
  DBT_PROJECT_DIR: ./coffee_shop  # Specify the location of the project directory
  SCHEMA_PREFIX: dbt_oriana_ga_pr  # Specify the prefix for the PR schema
  PROJECT_ID: ${{ secrets.BIGQUERY_PROJECT_ID }}  # Update with the name of the secret containing the project ID
  SERVICE_ACCOUNT_KEY: ${{ secrets.BIGQUERY_SERVICE_ACCOUNT_KEY }}  # Update with the name of the secret containing the service account key

jobs:
  run-production-models:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # Checkout the specific commit of the pull request

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11  # Choose the Python version you need

      - name: Install requirements
        run: |
          pip install -r requirements.txt
      
      - name: Create GCP keyfile JSON
        run: |
          echo "$BIGQUERY_SERVICE_ACCOUNT_KEY" > $DBT_PROFILES_DIR/gcp-credentials.json
          
      - name: Configure dbt Profile
        run: |
          echo "
          coffee_shop:
            target: prod
            outputs:
              prod:
                type: bigquery
                method: service-account
                keyfile: $DBT_PROFILES_DIR/gcp-credentials.json
                project: $BIGQUERY_PROJECT_ID
                dataset: dbt_oriana_ga_prod
                threads: 4
                timeout_seconds: 300
          " > $DBT_PROFILES_DIR/profiles.yml

      - name: Run dbt
        run: |
          dbt run --profiles-dir "$DBT_PROFILES_DIR" --target prod --project-dir "$DBT_PROJECT_DIR"  

      - name: Generate dbt docs
        run: dbt docs generate

      - name: Deploy dbt docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.DBT_PROJECT_DIR }}/target

  cleanup-schemas:
    if: github.event.pull_request.merged == true || github.event.pull_request.closed == true
    runs-on: ubuntu-latest
    needs: run-production-models
      
    steps:
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: '${{ secrets.BIGQUERY_SERVICE_ACCOUNT_KEY }}'
      
      - name: Remove PR Schema
        run: |
          PR_SCHEMA="${{ env.SCHEMA_PREFIX }}_${{ github.event.number }}"
          gcloud config set project $PROJECT_ID
          gcloud beta bq datasets delete $PR_SCHEMA
          --force