name: Run dbt test suite on PRs

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  push:
    branches:
      - '!main'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DBT_PROFILES_DIR: ./coffee_shop  # Specify the location of the profiles.yml file
      DBT_PROJECT_DIR: ./coffee_shop  # Specify the location of the project directory
      SERVICE_ACCOUNT_KEY: ${{ secrets.BIGQUERY_SERVICE_ACCOUNT_KEY }}
      
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # Checkout the specific commit of the pull request

      - name: Create GCP keyfile JSON
        run: | # Creates the keyfile and moves it to the profiles directory
          echo "$SERVICE_ACCOUNT_KEY" > gcp-credentials.json
          mv gcp-credentials.json $DBT_PROFILES_DIR 

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11  # Choose the Python version you need

      - name: Install dbt-bigquery
        run: |
          pip install dbt-bigquery
          dbt debug --target ci

      - name: Run dbt build
        run: |
          dbt build --profiles-dir "$DBT_PROFILES_DIR" --target ci --project-dir "$DBT_PROJECT_DIR"